### ISSUE TITLE
provide a solution for object serialization and deserialization (for kafka)

### ISSUE THREAD

**Issue by tammyzhang123** [cloudevents/sdk-java#395]
Can you provide a best practice solution for object serialization and deserialization (for kafka)?
When I use the io.cloudevents.examples.kafka.SampleProducer provided on Git to produce data to Kafka, the error "CloudEventSerializer supports only the signature serialize(String, Headers, CloudEvent)" will appear. Same goes for deserialization.

**Comment by slinkydeveloper** [comment]
That's strange, can you provide more details/stacktrace? That error shouldn't happen...

**Comment by tammyzhang123** [comment]
When I run this class (io.cloudevents.examples.kafka.SampleConsumer)，  the following error appears:
Exception in thread "main" org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition CloudEventTopic-0 at offset 80. If needed, please seek past the record to continue consumption.
Caused by: java.lang.UnsupportedOperationException: CloudEventDeserializer supports only the signature deserialize(String, Headers, byte[])
	at io.cloudevents.kafka.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:57)
	at io.cloudevents.kafka.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:36)
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:65)
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:55)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1009)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:96)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1186)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1500(Fetcher.java:1035)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:544)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:505)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1259)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at io.cloudevents.examples.kafka.SampleConsumer.main(SampleConsumer.java:41)

**Comment by slinkydeveloper** [comment]
Which version of kafka are you using?

**Comment by tammyzhang123** [comment]
The version of kafka I use is 2.2.0, what is the latest version of Kafka supported by cloudevents?

**Comment by slinkydeveloper** [comment]
Whatever version of kafka that supports header should work fine... So you sent messages to kafka using SampleProducer, right?

**Comment by tammyzhang123** [comment]
yes, i sent messages to kafka using SampleProducer

**Comment by slinkydeveloper** [comment]
Just tried myself and I wasn't able to reproduce the issue... Can you check that the records inside kafka contains the content type header?

You can do it with [kafkacat](https://github.com/edenhill/kafkacat):

```
$ kafkacat -b localhost:9092 -C -f '\nKey (%K bytes): %k\t\nHeaders: %h\nValue (%S bytes): %s\n\Partition: %p\tOffset: %o\n--\n' -t sample-topic

Key (36 bytes): 2bb63f0b-ccd9-4241-a8a4-c6b11a64c506	
Headers: content-type=application/cloudevents+json
Value (237 bytes): {"specversion":"1.0","id":"2bb63f0b-ccd9-4241-a8a4-c6b11a64c506","source":"https://github.com/cloudevents/sdk-java/tree/master/examples/kafka","type":"producer.example","datacontenttype":"text/plain","data_base64":"RXZlbnQgbnVtYmVyIDA="}
Partition: 0	Offset: 0
```

**Comment by tammyzhang123** [comment]
First and foremost, I can't run the SampleProducer program. Because the program reports an error: java.lang.UnsupportedOperationException: CloudEventSerializer supports only the signature serialize(String, Headers, CloudEvent), the meaasge can't be written to kafka,i am so confused.

**Comment by slinkydeveloper** [comment]
TBH I'm confused too, I thought the problem was the consumer... I tried both the examples myself and everything works fine, I need more info from you in order to help you.

**Comment by tammyzhang123** [comment]
Could you send me a copy of your code demo?  I want to see what is the difference between the two. My mail address is：tammy03272021@163.com

**Comment by slinkydeveloper** [comment]
@tammyzhang123 I just cloned the latest master and run it, following the readme...

**Comment by tammyzhang123** [comment]
OK， i'll try it
