### ISSUE TITLE
 Could not parse. Unknown encoding. Invalid content type or spec version

### ISSUE THREAD

**Issue by sumitbaurai** [cloudevents/sdk-java#401]
Hi, 

I am trying to parse events published by Kafka. These events are audit events, that are published by Kafka Brokers in case of for example, an  authentication attempt.

Here are the details of the event:

Header contains : 

`content-type : application/cloudevents+json`

Value Contains: 

```
{
  "data" : { 
    "serviceName" : "crn:///kafka=JAlahGL_TUmLkqN_24KC2A",
    "methodName" : "kafka.Authentication",
    "resourceName" : "crn:///kafka=JAlahGL_TUmLkqN_24KC2A",
    "authenticationInfo" : {
      "principal" : "User:kafka",
      "metadata" : {
        "mechanism" : "SASL_PLAINTEXT/SCRAM-SHA-256",
        "identifier" : "kafka"
      }
    },
    "requestMetadata" : {
      "client_address" : "/10.44.168.161"
    },
    "result" : {
      "status" : "SUCCESS",
      "message" : ""
    }
  },
  "id" : "84040a3c-e5d4-46ea-b92d-462b020c86f8",
  "source" : "crn:///kafka=JAlahGL_TUmLkqN_24KC2A",
  "specversion" : "1.0",
  "type" : "io.confluent.kafka.server/authentication",
  "datacontenttype" : "application/json",
  "subject" : "crn:///kafka=JAlahGL_TUmLkqN_24KC2A",
  "time" : "2021-06-21T13:48:42.377Z",
  "confluentRouting" : {
    "route" : "confluent-audit-log-events"
  }
}
```

When I try to deserialize this message in a Kafka Consumer, using CloudEventDeserializer.class

`props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, CloudEventDeserializer.class);`

It throws an exception : 

```
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition audit-producer-topic-1-0 at offset 6. If needed, please seek past the record to continue consumption.
Caused by: io.cloudevents.rw.CloudEventRWException: Could not parse. Unknown encoding. Invalid content type or spec version
	at io.cloudevents.rw.CloudEventRWException.newUnknownEncodingException(CloudEventRWException.java:201)
	at io.cloudevents.core.message.impl.MessageUtils.parseStructuredOrBinaryMessage(MessageUtils.java:80)
```

Upon inspection of the MesasgeUtils.java class, it has the following check

```
public static MessageReader parseStructuredOrBinaryMessage(Supplier<String> contentTypeHeaderReader, Function<EventFormat, MessageReader> structuredMessageFactory, Supplier<String> specVersionHeaderReader, Function<SpecVersion, MessageReader> binaryMessageFactory) throws CloudEventRWException {
        String ct = (String)contentTypeHeaderReader.get();
        if (ct != null) {
            EventFormat format = EventFormatProvider.getInstance().resolveFormat(ct);
            if (format != null) {
                return (MessageReader)structuredMessageFactory.apply(format);
            }

            if (ct.startsWith("application/cloudevents")) {
                throw CloudEventRWException.newUnknownEncodingException();
            }
        }
```

According to documentation, application/cloudevents+json is a valid content type, then why is an exception being thrown for that?

Any explanation around this would be useful.. 

Thanks in advance !!

**Comment by slinkydeveloper** [comment]
Do you have cloudevents-json-jackson in your classpath? https://cloudevents.github.io/sdk-java/json-jackson.html

> `"confluentRouting"`

This is an invalid extension key, attribute name must be all lowercase chars. Although, I don't think this is the reason for that exception

**Comment by sumitbaurai** [comment]
Hi, No change after adding the cloudevents-json-jackson dependency. Still running into the same issue.

```
[2021-06-23 09:19:10,800] INFO [Consumer clientId=consumer-audit-consumer-4-1, groupId=audit-consumer-4] Resetting offset for partition confluent-audit-log-events-0 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[clrv0000156427.ic.ing.net:9092 (id: 3 rack: null)], epoch=21}}. (org.apache.kafka.clients.consumer.internals.SubscriptionState)
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition confluent-audit-log-events-0 at offset 0. If needed, please seek past the record to continue consumption.
Caused by: io.cloudevents.rw.CloudEventRWException: Could not parse. Unknown encoding. Invalid content type or spec version
	at io.cloudevents.rw.CloudEventRWException.newUnknownEncodingException(CloudEventRWException.java:201)
	at io.cloudevents.core.message.impl.MessageUtils.parseStructuredOrBinaryMessage(MessageUtils.java:69)
	at io.cloudevents.kafka.KafkaMessageFactory.createReader(KafkaMessageFactory.java:65)
	at io.cloudevents.kafka.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:60)
	at io.cloudevents.kafka.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:34)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1387)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:133)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1618)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1454)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:687)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:638)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1299)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
```

**Comment by slinkydeveloper** [comment]
Are you using the latest 2.2 version of the sdk?

**Comment by sumitbaurai** [comment]
yes..thats the version i use

**Comment by slinkydeveloper** [comment]
Can you try to debug the `EventFormatProvider` and see if the `JsonFormat` is loaded inside it? From the stacktrace, the error seems to be that you don't have the `JsonFormat` loaded properly...

**Comment by vbkunin** [comment]
Adding cloudevents-json-jackson to classpath solved the problem for me.

**Comment by pierDipi** [comment]
@sumitbaurai, are you still getting this error? Do suggested fixes solve your issue?

**Comment by sumitbaurai** [comment]
Hi, Indeed including the jackson dependency resolves the deserialization issue.

**Comment by plopp** [comment]
I was struggling with this error but only when running my spring application from a fat jar. Spring `bootRun` worked flawlessly, but `java -jar <...>` caused the error above. It was indeed that the `JsonFormat` was not registered with the `EventFormatProvider`. I had to do this to get it to work also when running the jar (non relevant code left out):

```
...
import io.cloudevents.jackson.JsonFormat; // <---
import io.cloudevents.core.provider.EventFormatProvider; // <---
...

@SpringBootApplication
public class MyApp {
    public static void main(String[] args) {
        EventFormatProvider.getInstance().registerFormat(new JsonFormat()); // <---
        SpringApplication.run(MyApp.class, args);
    }
}
```
