### ISSUE TITLE
NPE unmarshalling an event

### ISSUE THREAD

**Issue by gee4vee** [cloudevents/sdk-java#63]
I'm using Spring for REST and trying to unmarshall an event coming in with this code snippet:

```    
@PostMapping(value = "/", consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> event(@RequestHeader Map<String, Object> headers,
            @RequestBody String body) {
        System.out.println("Receved request headers: " + headers);
        System.out.println("Received request body: " + body);
        if (MediaType.APPLICATION_JSON_VALUE.equalsIgnoreCase(headers.get("content-type").toString())) {
            @SuppressWarnings("rawtypes")
            CloudEvent<AttributesImpl, Map> cloudEvent = Unmarshallers.binary(Map.class)
                .withHeaders(() -> headers)
                .withPayload(() -> body)
                .unmarshal();
            System.out.println("Received CloudEvent: " + cloudEvent);
            //...
        }
        return ResponseEntity.accepted().build();
    }
```

I get these headers and body:
```
Receved request headers: {host=****, user-agent=Go-http-client/1.1, content-length=40, accept-encoding=gzip, ce-id=81063005-d897-4162-8a79-5224bdde4d81, ce-source=/apis/v1/namespaces/default/cronjobsources/test-cronjob-source, ce-specversion=0.3, ce-time=2019-10-08T12:56:00.000398275Z, ce-type=dev.knative.cronjob.event, content-type=application/json, forwarded=for=172.30.252.225;proto=http, for=127.0.0.1, k-proxy-request=activator, x-b3-parentspanid=08fdcef844c5b6e6, x-b3-sampled=0, x-b3-spanid=7d2298100968d43e, x-b3-traceid=ff56838a09c39d245ad334a89c91a0c8, x-envoy-decorator-operation=javaspringknativecloudant-vwv5h-nlf5f.default.svc.cluster.local:80/*, x-forwarded-for=172.30.252.225, 127.0.0.1, 172.30.233.147, x-forwarded-proto=http, x-istio-attributes=ClsKF2Rlc3RpbmF0aW9uLnNlcnZpY2UudWlkEkASPmlzdGlvOi8vZGVmYXVsdC9zZXJ2aWNlcy9qYXZhc3ByaW5na25hdGl2ZWNsb3VkYW50LXZ3djVoLW5sZjVmCl0KGGRlc3RpbmF0aW9uLnNlcnZpY2UuaG9zdBJBEj9qYXZhc3ByaW5na25hdGl2ZWNsb3VkYW50LXZ3djVoLW5sZjVmLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwKQwoYZGVzdGluYXRpb24uc2VydmljZS5uYW1lEicSJWphdmFzcHJpbmdrbmF0aXZlY2xvdWRhbnQtdnd2NWgtbmxmNWYKKgodZGVzdGluYXRpb24uc2VydmljZS5uYW1lc3BhY2USCRIHZGVmYXVsdApHCgpzb3VyY2UudWlkEjkSN2t1YmVybmV0ZXM6Ly9hY3RpdmF0b3ItNzY1NDc1OTU0Ny00ZDd2bS5rbmF0aXZlLXNlcnZpbmc=, x-request-id=6041ed42-e2e0-46b5-b6eb-c5ff88120464}
Received request body: {"message":"Hello world! This is CRON!"}
```

And I get this NPE. Am I doing something wrong in my usage of the SDK?
```
java.lang.NullPointerException: null
	at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(Unknown Source) ~[na:1.8.0]
	at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(Unknown Source) ~[na:1.8.0]
	at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(Unknown Source) ~[na:1.8.0]
	at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(Unknown Source) ~[na:1.8.0]
	at java.lang.reflect.Field.getAnnotatedType(Unknown Source) ~[na:1.8.0]
	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForMember(TypeAnnotationAwareMetaDataProvider.java:65) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:244) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:227) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:137) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:125) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfigurationForHierarchy(AnnotationMetaDataProvider.java:108) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:203) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:231) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.isConstrained(BeanMetaDataManager.java:174) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:195) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at io.cloudevents.v02.CloudEventBuilder.build(CloudEventBuilder.java:183) ~[cloudevents-api-0.3.1.jar!/:na]
	at io.cloudevents.v02.CloudEventBuilder.of(CloudEventBuilder.java:158) ~[cloudevents-api-0.3.1.jar!/:na]
	at io.cloudevents.v02.CloudEventBuilder.build(CloudEventBuilder.java:164) ~[cloudevents-api-0.3.1.jar!/:na]
	at io.cloudevents.v02.http.Unmarshallers$$Lambda$22.00000000182159E0.build(Unknown Source) ~[na:na]
	at io.cloudevents.format.BinaryUnmarshaller$Builder.unmarshal(BinaryUnmarshaller.java:241) ~[cloudevents-api-0.3.1.jar!/:na]
	at application.rest.v1.Events.event(Events.java:75) ~[classes!/:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
```

**Comment by fabiojose** [comment]
@gee4vee 
I have some question:

- What is the spec version 0.2 or 0.3?
- What is your JDK version?

**Comment by gee4vee** [comment]
spec v0.2, Java 1.8, Spring Boot 2.1.9

**Comment by gee4vee** [comment]
@fabiojose At times I'm getting a different exception. I guess it depends on the contents of the event. In this case events are coming from the standard CRON job source. I can get you access to the repo if you have a GitLab ID.
```
Receved request headers: {host=javaspringknativecloudant.default.svc.cluster.local, user-agent=Go-http-client/1.1, content-length=40, accept-encoding=gzip, ce-id=bc3fed85-d2a0-4b84-9f90-ae16a2fb0892, ce-source=/apis/v1/namespaces/default/cronjobsources/test-cronjob-source, ce-specversion=0.3, ce-time=2019-10-09T16:14:00.000382137Z, ce-type=dev.knative.cronjob.event, content-type=application/json, forwarded=for=172.30.252.225;proto=http, for=127.0.0.1, k-proxy-request=activator, x-b3-parentspanid=ba0888c30a0d26bf, x-b3-sampled=0, x-b3-spanid=da0b2fd9aeabcfd7, x-b3-traceid=4714a46b9e8e64727e2dbc1b373ec5d0, x-envoy-decorator-operation=javaspringknativecloudant-9fkw4-6rmwh.default.svc.cluster.local:80/*, x-forwarded-for=172.30.252.225, 127.0.0.1, 172.30.233.147, x-forwarded-proto=http, x-istio-attributes=CioKHWRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZXNwYWNlEgkSB2RlZmF1bHQKQwoYZGVzdGluYXRpb24uc2VydmljZS5uYW1lEicSJWphdmFzcHJpbmdrbmF0aXZlY2xvdWRhbnQtOWZrdzQtNnJtd2gKRwoKc291cmNlLnVpZBI5EjdrdWJlcm5ldGVzOi8vYWN0aXZhdG9yLTc2NTQ3NTk1NDctNGQ3dm0ua25hdGl2ZS1zZXJ2aW5nClsKF2Rlc3RpbmF0aW9uLnNlcnZpY2UudWlkEkASPmlzdGlvOi8vZGVmYXVsdC9zZXJ2aWNlcy9qYXZhc3ByaW5na25hdGl2ZWNsb3VkYW50LTlma3c0LTZybXdoCl0KGGRlc3RpbmF0aW9uLnNlcnZpY2UuaG9zdBJBEj9qYXZhc3ByaW5na25hdGl2ZWNsb3VkYW50LTlma3c0LTZybXdoLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=, x-request-id=dc634037-aa02-4cb1-a35a-bac28f205c2f}
Received request body: {"message":"Hello world! This is CRON!"}
Exception caught retrieving events
java.lang.RuntimeException: Failed to invoke java.time.ZoneId() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:865)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:229)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:334)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:85)
	at com.cloudant.client.api.Database.find(Database.java:550)
	at application.events.CloudEventStoreCloudant.getEvents(CloudEventStoreCloudant.java:51)
	at application.rest.v1.Events.events(Events.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:110)
	... 81 more
```

**Comment by fabiojose** [comment]
I see `at com.google.gson.internal.ConstructorConstructor$3.construct(`. We do not use gson.

**Comment by fabiojose** [comment]
> GitLab ID.

Yes, I have `fabiojose`. Ping me when you grant access

**Comment by fabiojose** [comment]
> I see `at com.google.gson.internal.ConstructorConstructor$3.construct(`. We do not use gson.

gson cant work with ZonedDatetime use as the type of `time` attribute.

**Comment by fabiojose** [comment]
As I suspected. We use hibernate validator: 6.0.17.Final

```xml
<hibernate-validator.version>6.0.17.Final</hibernate-validator.version>
```

And the error shows a old one: 5.3.6.Final

```txt
	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForMember(TypeAnnotationAwareMetaDataProvider.java:65) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:244) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
```

Please, list all dependencies in your pom.xml.

**Comment by gee4vee** [comment]
> > GitLab ID.
> 
> Yes, I have `fabiojose`. Ping me when you grant access

I cannot find you on GitLab (which is different than GitHub). This is the repo:
https://us-south.git.cloud.ibm.com/gvalenc/nickfs-springcloudantknative/-/project_members

**Comment by gee4vee** [comment]
> As I suspected. We use hibernate validator: 6.0.17.Final
> 
> ```
> <hibernate-validator.version>6.0.17.Final</hibernate-validator.version>
> ```
> 
> And the error shows a old one: 5.3.6.Final
> 
> ```
> 	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForMember(TypeAnnotationAwareMetaDataProvider.java:65) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
> 	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:244) ~[hibernate-validator-5.3.6.Final.jar!/:5.3.6.Final]
> ```
> 
> Please, list all dependencies in your pom.xml.

This is my pom.xml:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>projects</groupId>
  <artifactId>knative-eventing</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <java.version>1.8</java.version>
    
    <spring-boot.version>2.1.9.RELEASE</spring-boot.version>
    <opentracing-spring-jaeger-web-starter.version>2.0.0</opentracing-spring-jaeger-web-starter.version>
    <app.name>knative-eventing</app.name>
  </properties>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.9.RELEASE</version>
  </parent>

  <dependencies>
   <!-- Core -->
   <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
    
    <!-- Monitoring -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>

    <!-- Distributed tracing with OpenTracing -->
    <dependency>
        <groupId>io.opentracing.contrib</groupId>
        <artifactId>opentracing-spring-jaeger-web-starter</artifactId>
        <version>${opentracing-spring-jaeger-web-starter.version}</version>
    </dependency>
    
    <!-- Application -->
    <dependency>
        <groupId>io.cloudevents</groupId>
        <artifactId>cloudevents-api</artifactId>
        <version>0.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.cloudant</groupId>
      <artifactId>cloudant-spring-boot-starter</artifactId>
      <version>0.0.2</version>
    </dependency>
    <dependency>
      <groupId>com.ibm.cloud</groupId>
      <artifactId>ibm-cloud-spring-boot-service-bind</artifactId>
      <version>1.1.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-collections4</artifactId>
        <version>4.4</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>
```

**Comment by gee4vee** [comment]
> I see `at com.google.gson.internal.ConstructorConstructor$3.construct(`. We do not use gson.

Yes this seems to be related to a Java Cloudant Client issue. I will look into it separately, thanks.

**Comment by gee4vee** [comment]
So adding this to my pom fixed it. Thanks!
```
<hibernate-validator.version>6.0.17.Final</hibernate-validator.version>
```
