### ISSUE TITLE
java.lang.IllegalStateException: Failed to decode when unmarshalling event

### ISSUE THREAD

**Issue by gee4vee** [cloudevents/sdk-java#64]
I have a unit test incorporating Spring Boot and CloudEvents:

```
    @Test
    public void testEventEndpoint() throws Exception {
        String endpoint = "http://localhost:" + port + "/";
        Map<String, String> testValue = new HashMap<>();
        testValue.put("test", "value");
        String body = Json.encode(testValue);
        
        /*Create a tracing extension*/
        final DistributedTracingExtension dt = new DistributedTracingExtension();
        dt.setTraceparent("0");
        dt.setTracestate("congo=4");
        /*Format it as extension format*/
        final ExtensionFormat tracing = new DistributedTracingExtension.Format(dt);
        /* Build a CloudEvent instance */
        CloudEventImpl<String> ce =
            CloudEventBuilder.<String>builder()
                .withType("knative.eventing.test")
                .withSource(URI.create("https://github.com/cloudevents/spec/pull"))
                .withId("A234-1234-1234")                   
                .withTime(ZonedDateTime.now())
                .withContenttype(MediaType.APPLICATION_JSON_VALUE)
                .withData(body)
                .withExtension(tracing)
                .build();

        /* Marshal the event as a Wire instance and grab the headers and body*/
        Wire<String, String, String> wire = Marshallers.<String>binary()
                .withEvent(() -> ce)
                .marshal();
        Map<String, String> headerVals = wire.getHeaders();
        HttpHeaders headers = new HttpHeaders();
        for (Entry<String, String> entry : headerVals.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();
            List<String> vals;
            if (headers.containsKey(key)) {
                vals = headers.get(key);
            } else {
                vals = new ArrayList<>();
                headers.put(key, vals);
            }
            vals.add(value);
        }

        System.out.println("Cloud Event headers: " + headers);
        System.out.println("Cloud Event body: " + wire.getPayload().get());
        HttpEntity<String> request = new HttpEntity<>(wire.getPayload().get(), headers);
        ResponseEntity<Void> result = this.server.postForEntity(new URI(endpoint), request, Void.class);
        assertEquals("Unexpected response code", HttpStatus.ACCEPTED, result.getStatusCode());
        
        endpoint = "http://localhost:" + port + "/v1/events";
        String response = server.getForObject(endpoint, String.class);
        System.out.println("Events server response: " + response);
        assertFalse("Error response from server", response.startsWith("ERROR"));
        assertFalse("Warning response from server", response.startsWith("WARNING"));
        assertTrue("Unexpected events response from server: " + response, response.startsWith("NUMBER OF EVENTS"));
    }
```

The test is failing with this exception. It appears to be unable to handle the JSON string I'm passing in as the body. Am I doing something wrong in the unit test?
```
Cloud Event headers: [ce-source:"https://github.com/cloudevents/spec/pull", tracestate:"congo=4", ce-specversion:"0.2", ce-type:"knative.eventing.test", ce-id:"A234-1234-1234", traceparent:"0", ce-time:"2019-10-09T14:51:18.529-05:00", Content-Type:"application/json"]
Cloud Event body: "{\"test\":\"value\"}"
Receved request headers: {accept=application/json, application/*+json, ce-source=https://github.com/cloudevents/spec/pull, tracestate=congo=4, ce-specversion=0.2, ce-type=knative.eventing.test, ce-id=A234-1234-1234, traceparent=0, ce-time=2019-10-09T14:51:18.529-05:00, uber-trace-id=3cfe6a1aff615223%3A3cfe6a1aff615223%3A0%3A1, content-type=application/json, content-length=22, host=localhost:64232, connection=Keep-Alive, accept-encoding=gzip, user-agent=okhttp/3.9.0}
Received request body: "{\"test\":\"value\"}"
2019-10-09 14:51:18.719  INFO 20641 --- [o-auto-1-exec-2] i.j.internal.reporters.LoggingReporter   : Span reported: 3cfe6a1aff615223:da07a85ce3d80d2c:3cfe6a1aff615223:1 - event
2019-10-09 14:51:18.729 ERROR 20641 --- [o-auto-1-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Failed to decode: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"test":"value"}')
 at [Source: (String)""{\"test\":\"value\"}""; line: 1, column: 1]] with root cause

java.lang.IllegalStateException: Failed to decode: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"test":"value"}')
 at [Source: (String)""{\"test\":\"value\"}""; line: 1, column: 1]
	at io.cloudevents.json.Json.decodeValue(Json.java:104) ~[cloudevents-api-0.3.1.jar:na]
	at io.cloudevents.json.Json$1.unmarshal(Json.java:220) ~[cloudevents-api-0.3.1.jar:na]
	at io.cloudevents.json.Json$1.unmarshal(Json.java:217) ~[cloudevents-api-0.3.1.jar:na]
	at io.cloudevents.format.BinaryUnmarshaller$Builder.lambda$unmarshal$2(BinaryUnmarshaller.java:227) ~[cloudevents-api-0.3.1.jar:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_181]
	at io.cloudevents.format.BinaryUnmarshaller$Builder.unmarshal(BinaryUnmarshaller.java:226) ~[cloudevents-api-0.3.1.jar:na]
	at application.rest.v1.Events.event(Events.java:77) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
```

**Comment by fabiojose** [comment]
You must pass the map, not the json encoded string.

Instead of this
```java
CloudEventImpl<String> ce = ...
```

Do this:

```java
CloudEventImpl<Map> ce =...
```
Then, the Marshaller will do the Json.encode work, creating a valid json string.

The result body will be `"{"test":"value"}"`, not `"{\"test\":\"value\"}"` with trilling causing the error.

**Comment by gee4vee** [comment]
This worked, thanks!
